app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

api_get_token:
    path:     /api/token/get
    defaults: { _controller: AppBundle:Api/GetJWT:getToken }
    methods: ['POST']

api_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc/api
