fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

front_public:
    resource: "@AppBundle/Controller/Front"
    prefix:   /

front_admin:
    resource: "@AppBundle/Controller/Front/Admin"
    prefix:   /admin

api:
    resource: "@AppBundle/Controller/Api"
    prefix:   /api/v1/
