AppBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: AppBundle\Repository\UserRepository

    id:
        id:
            type: string
            length: 128
            generator: { strategy: custom }
            customIdGenerator: { class: AppBundle\Doctrine\ORM\Sha512Generator }
    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
